services:
  web:
    build:
      context: .
      dockerfile: deploy/flask/Dockerfile
    volumes:
      - .:/flask-onion
    expose:
      - 8000
    environment:
      FLASK_ENV: production

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/flask-onion/app/static
    depends_on:
      - web
